version: '3.5'

services:

  db_service:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_DOCKER_PORT:3306
    restart: unless-stopped
    networks:
      - laravel-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=docker_laravel
    volumes:
      - .:/var/www/html
      - ./docker-provision/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#      - ./docker-provision:/tmp
    ports:
      - $APP_DOCKER_PORT:80
    restart: unless-stopped
    depends_on:
      - db_service
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge
